name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "17 3 * * *"   # daily at 03:17 UTC
  workflow_dispatch:        # allow manual + programmatic trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-cards
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
